### PR TITLE
feat: ✨ Supports echarts

### PR DESCRIPTION
**Pull request by haydenull**

### CODE REVIEW

**Comment by haydenull** [comment]
Support for displaying charts using [echarts](https://echarts.apache.org/zh/index.html).

Example:

````markdown
```echarts
{"tooltip":{"trigger":"item"},"legend":{"top":"5%","left":"center"},"series":[{"name":"Access From","type":"pie","radius":["40%","70%"],"avoidLabelOverlap":false,"itemStyle":{"borderRadius":10,"borderColor":"#fff","borderWidth":2},"label":{"show":false,"position":"center"},"emphasis":{"label":{"show":true,"fontSize":40,"fontWeight":"bold"}},"labelLine":{"show":false},"data":[{"value":1048,"name":"Search Engine"},{"value":735,"name":"Direct"},{"value":580,"name":"Email"},{"value":484,"name":"Union Ads"},{"value":300,"name":"Video Ads"}]}]}
```
````

image

**Comment by sinjab** [comment]
I enabled the plugin then copied/pasted your echarts example into a logseq block but no chart appeared, just normal code block.

**Comment by AhmedThahir** [comment]
I'm getting block render error for your above example

**Comment by bixycler** [comment]
It should be noted that this plugin only supports `option` as the only content in **JSON** format.  
So, be careful when copying from JS codes, because no JS codes, e.g. `const`, function, lambda, are allowed in the `echarts` code block.

**Pull request merged**
